version: '3.8'

services:
  server:
    build: ./server
    container_name: schedu_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PG_HOST=db
      - PG_USER=admin
      - PG_PASSWORD=admin123
      - PG_DATABASE=schedu_db
      - PG_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  client:
    build: ./client
    container_name: schedu_client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - default

  db:
    image: postgres:13-alpine
    container_name: schedu_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=schedu_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # <-- ADD THIS LINE
      - schedu_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d schedu_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:

volumes:
  schedu_data: